name: CI

on:
  push:
    branches: '**'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: pip3 install editorconfig-checker vim-vint

      - run: ec

      - run: vint .
